name: Shadow Robot Documentation
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

title: "Shadow Robot Company"
repository: "beatrizleon/documentation"
breadcrumbs: true
search: true
include: ["_docs"]

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
